### PR TITLE
HostAndPort.convertHost() to resolve localhost in a lazy manner

### LINKED ISSUE #1424: Jedis should not require localhost to be resolved so it can run clean in serverless env
### Expected behavior
Jedis should not require localhost to be resolved so it can run clean in serverless env - aws lambda. 

### Actual behavior
When running jedis on aws lambda, it tries to resolve localhost which is not available in serverless env resulting in a "SEVERE" log output.

Write here what happens instead ...

    15:02:45 SEVERE: cant resolve localhost address
    15:02:45 java.net.UnknownHostException: ip-10-29-121-116: ip-10-29-121-116: unknown error
    15:02:45 at java.net.InetAddress.getLocalHost(InetAddress.java:1505)
    15:02:45 at redis.clients.jedis.HostAndPort.getLocalHostQuietly(HostAndPort.java:105)

### Steps to reproduce:
Use jedis client in aws lambda to connect to aws redis service endpoint
    public class RedisClientDao {

    private static JedisPool pool = null;

    static {
        String endpoint = Preconditions.checkNotNull((String)Config.get("CACHE_ENDPOINT"));
        JedisPoolConfig poolConfig = new JedisPoolConfig();
        poolConfig.setJmxEnabled(false);
        pool = new JedisPool(poolConfig, endpoint);

    }

    public static Jedis getRedisClient() {
        return pool.getResource();
    }
    }

### Redis / Jedis Configuration
jedis 2.9.0 running on java 1.8 running on aws lambda connecting to redis 3.2.4

#### Jedis version:
2.9
#### Redis version:
3.2.4
#### Java version:
1.8

### PR DESCRIPTION
**Pull request by jkrahul**
fixes #1424

### CODE REVIEW

**Comment by jkrahul** [comment]
There is some issue with redis dependencies in Travis. Tests passed in my local with `redis unstable branch`

**Comment by marcosnils** [comment]
LGTM @HeartSaVioR ?

**Comment by marcosnils** [comment]
@jkrahul can you rebase with master so tests pass please?

File: src/main/java/redis/clients/jedis/HostAndPort.java [hunk 1]
```diff
@@ -90,15 +90,50 @@ public static HostAndPort parseString(String from){
...
+        return host;
+    } catch (Exception e) {
+      // Not a valid IP address
+      log.logp(Level.WARNING, HostAndPort.class.getName(), "convertHost", "'" + host + "' is not a valid IP address",
+              e);
       return host;
     }
   }
 
+  public static void setLocalhost(String localhost) {
```
Comment (HeartSaVioR) [inline src/main/java/redis/clients/jedis/HostAndPort.java]: Are there any actual usages for `setLocalhost()`? `setLocalhost()` and `getLocalhost()` can make race condition. 

Btw, `getLocalhost()` itself can make race condition but it might be OK given that `getLocalHostQuietly()` always returns same value.

**Comment by HeartSaVioR** [comment]
@jkrahul I've done reviewing and left comment.

File: src/main/java/redis/clients/jedis/HostAndPort.java (hunk 1 above)
Comment (allanwax) [inline src/main/java/redis/clients/jedis/HostAndPort.java]: @marcosnils @jkrahul The only use I can think of is a potential one.  If the programmer wants to override the natural local host value, say with the `ENDPOINT` value, then they can make this call change it.  This would be done before actually creating a Jedis instance.

Comment (HeartSaVioR) [inline src/main/java/redis/clients/jedis/HostAndPort.java]: @jkrahul @allanwax 
If we want to keep this as it is, let's leave a javadoc comment for this method describing that this method is not thread-safe so it shouldn't be used with getLocalhost() concurrently.

**Comment by HeartSaVioR** [comment]
@jkrahul Please rebase and address review comment. Thanks in advance!

File: src/main/java/redis/clients/jedis/HostAndPort.java (hunk 1 above)
Comment (allanwax) [inline src/main/java/redis/clients/jedis/HostAndPort.java]: Wrapping the operations inside `setLocalhost` and `getLocalhost` will make it safe and is less heavy weight than `synchronized`.

**Comment by jkrahul** [comment]
@marcosnils @HeartSaVioR @allanwax review comments have been addressed. Please check

**Comment by marcosnils** [comment]
I believe we're good now. @allanwax @HeartSaVioR ?

File: src/main/java/redis/clients/jedis/HostAndPort.java (hunk 1 above)
Comment (allanwax) [inline src/main/java/redis/clients/jedis/HostAndPort.java]: @marcosnills @jkrahul I was imagining the wrapping being a ReentrantLock.  I'm good .

**Comment by HeartSaVioR** [comment]
@marcosnils Yes LGTM.

**Comment by HeartSaVioR** [comment]
Merged to master and 2.10 respectively. @jkrahul Thanks for contribution!
