### PR TITLE
validating URI before connecting

### LINKED ISSUE #850: NullPointerException initializing JedisPool with URI with no path
When constructing a JedisPool using the URI constructor, if you supply a minimalist basic URI without path, such as `localhost:6379`, the result is an NPE in the `JedisURIHelper`:

```java
  public static Integer getDBIndex(URI uri) {
    String[] pathSplit = uri.getPath().split("/", 2);  // <-- Exception here, because uri.getPath() is null
    if (pathSplit.length > 1) {
    // ...
    }
  }
```

### PR DESCRIPTION
**Pull request by nykolaslima**
closes #850 

@HeartSaVioR @marcosnils

### CODE REVIEW

**Comment by marcosnils** [comment]
@nykolaslima LGTM. @bennesher what do you think?

**Comment by bennesher** [comment]
@nykolaslima LGTM too!

File: src/main/java/redis/clients/jedis/JedisPool.java [hunk 1]
```diff
@@ -27,7 +27,7 @@ public JedisPool(String host, int port) {
 
   public JedisPool(final String host) {
     URI uri = URI.create(host);
```
Comment (HeartSaVioR) [inline src/main/java/redis/clients/jedis/JedisPool.java]: Seems like we can call this(new GenericObjectPoolConfig(), URI.create(host)); instead of extracting partial URL values to remove duplication.
Could you please check? :)

**Comment by HeartSaVioR** [comment]
I've commented one thing about removing duplication, but it's trivial thing. 
LGTM, too.
After verifying my comments are valid, and applying if it's valid, I'll merge this.

File: src/main/java/redis/clients/jedis/JedisShardInfo.java [hunk 2]
```diff
@@ -31,7 +32,7 @@ public int getPort() {
   public JedisShardInfo(String host) {
     super(Sharded.DEFAULT_WEIGHT);
```
Comment (HeartSaVioR) [inline src/main/java/redis/clients/jedis/JedisShardInfo.java]: Seems like we can call this(URL.create(host)) instead of extracting partial URL values to remove duplication.
Could you please check? :)

File: src/main/java/redis/clients/jedis/JedisPool.java (hunk 1 above)
Comment (nykolaslima) [inline src/main/java/redis/clients/jedis/JedisPool.java]: @HeartSaVioR we can call `this(new GenericObjectPoolConfig(), URI.create(host))` because call another constructor must be the first command inside the constructor.

We could change the entire constructor to delegate to `this(new GenericObjectPoolConfig(), URI.create(host))`, but doing this, if the URI is invalid we will thrown one exception instead of trying to build the `GenericObjectPoll` with host string. I think that's not the desired action.

File: src/main/java/redis/clients/jedis/JedisShardInfo.java (hunk 2 above)
Comment (nykolaslima) [inline src/main/java/redis/clients/jedis/JedisShardInfo.java]: Same here. If we delegate to another constructor, we will thrown a `InvalidURIException` instead of setting the host string with the default port.

Comment (HeartSaVioR) [inline src/main/java/redis/clients/jedis/JedisShardInfo.java]: @nykolaslima OK, I can see "else" state. 
We can remove duplication by adding new setup method which is like BinaryJedis.initializeClientFromURI(), but current state is acceptable.

**Comment by HeartSaVioR** [comment]
LGTM, too. I'll merge this in.

File: src/main/java/redis/clients/jedis/JedisPool.java (hunk 1 above)
Comment (HeartSaVioR) [inline src/main/java/redis/clients/jedis/JedisPool.java]: @nykolaslima I see, thanks for explanation. :)

**Comment by HeartSaVioR** [comment]
@nykolaslima Thanks for your effort. Merged into master, 2.6, 2.7 branches.

**Comment by nykolaslima** [comment]
No problem @HeartSaVioR. Thank you for supporting me :)
